# Generated by Django 5.2 on 2025-04-30 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0003_cv'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='job',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rest_api.job'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='is_employer',
            field=models.BooleanField(default=False),
        ),
    ]
