# Generated by Django 5.2 on 2025-05-01 04:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0004_cv_job_alter_user_is_employer'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='job',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rest_api.job'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='cv_file',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
    ]
